name: Deploy ESP Launchpad to Pages

on:
  push:
    branches: ["main"]
    paths: 
      - 'launchpad/**'
      - '.github/workflows/launchpad-pages.yml'
  release:
    types: [published]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "launchpad-pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Clone ESP Launchpad
        run: |
          git clone https://github.com/espressif/esp-launchpad.git temp-launchpad
          
      - name: Download latest release binaries
        run: |
          # Create firmware directory
          mkdir -p temp-launchpad/firmware
          
          # Get the latest release and download firmware binaries
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/georgik/esp32-fruitland/releases/latest | jq -r '.tag_name')
          echo "Latest release: $LATEST_RELEASE"
          
          # Download firmware binaries from latest release
          curl -L -o temp-launchpad/firmware/esp32-fruitland-latest-esp-box-3.bin \
            "https://github.com/georgik/esp32-fruitland/releases/latest/download/esp32-fruitland-${LATEST_RELEASE}-esp-box-3.bin" || echo "ESP32-S3-BOX-3 binary not found"
          
          curl -L -o temp-launchpad/firmware/esp32-fruitland-latest-m5stack_core_s3.bin \
            "https://github.com/georgik/esp32-fruitland/releases/latest/download/esp32-fruitland-${LATEST_RELEASE}-m5stack_core_s3.bin" || echo "M5Stack CoreS3 binary not found"
          
          curl -L -o temp-launchpad/firmware/esp32-fruitland-latest-m5stack_tab5.bin \
            "https://github.com/georgik/esp32-fruitland/releases/latest/download/esp32-fruitland-${LATEST_RELEASE}-m5stack_tab5.bin" || echo "M5Stack Tab5 binary not found"

          curl -L -o temp-launchpad/firmware/esp32-fruitland-latest-esp32_p4_function_ev_board.bin \
            "https://github.com/georgik/esp32-fruitland/releases/latest/download/esp32-fruitland-${LATEST_RELEASE}-esp32_p4_function_ev_board.bin" || echo "ESP32-P4 Function EV binary not found"

          curl -L -o temp-launchpad/firmware/esp32-fruitland-latest-esp32_s3_lcd_ev_board.bin \
            "https://github.com/georgik/esp32-fruitland/releases/latest/download/esp32-fruitland-${LATEST_RELEASE}-esp32_s3_lcd_ev_board.bin" || echo "ESP32-S3 LCD EV binary not found"

      - name: Setup custom configuration
        run: |
          # Copy our configuration over the default one
          cp launchpad/config/config.toml temp-launchpad/config/config.toml
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          cd temp-launchpad
          npm install
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'temp-launchpad'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4